dependencies:
  - python=3.8.*
  - pip
  - pip:
    - --find-links https://download.pytorch.org/whl/cu113/torch_stable.html
    - fvcore>=0.1.5
    - torch>=1.10
    - torchvision>=0.11
    - pytorchvideo==0.1.5
    - matplotlib
    - tensorboard
    - tqdm
    - simplejson
    - yacs